//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio_tec
    {
        public int id { get; set; }
        public string titulo_sertec { get; set; }
        public string descripcion_sertec { get; set; }
        public int estado { get; set; }
        public string correo_personal { get; set; }
    }
}
