//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities1 : DbContext
    {
        public DBEntities1()
            : base("name=DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pregunta> pregunta { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<servicio_tec> servicio_tec { get; set; }
        public virtual DbSet<tienda> tienda { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
